In [95]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

#### Q1. In a school, there are total 100 students numbered from 1 to 100. You’re given three lists named ‘C’, ‘F’, and ‘H’, representing students who play cricket, football, and hockey, respectively. Based on this information, find out and print the following: 
- Students who play all the three sports
- Students who play both cricket and football but don’t play hockey
- Students who play exactly two of the sports
- Students who don’t play any of the three sports

#### 1. Which are the students who play all the three sports?
- [22, 39]
- [39, 82]
- [40, 95]
- [82, 94]

#### 2. Which are the players who play both cricket and hockey but don't play football?
- [20, 21, 25, 62, 67, 71, 75, 76, 82]
- [20, 21, 22, 25, 30, 32, 34]
- [20, 21, 22, 25, 30, 32, 34, 39, 43, 44, 62]
- [20, 21, 68, 71, 75, 76]

#### 3. How many players play exactly two sports?
- 19
- 20
- 21
- 22

#### 4. Which of these students do not play any of the sports? (More than one option may be correct)
- 41
- 48
- 63
- 85

In [96]:
C = [7, 8, 9, 18, 20, 21, 25, 26, 27, 31, 32, 34, 35, 36, 40, 43, 45, 47, 53, 58, 62, 67, 68, 71, 72, 74, 75, 76, 80, 81, 82, 90, 93, 95, 97, 99]
F = [1, 7, 10, 13, 16, 22, 24, 29, 30, 32, 34, 39, 40, 43, 44, 48, 56, 60, 65, 68, 69, 73, 77, 78, 90, 93, 94, 95, 96]
H = [5, 12, 14, 17, 20, 21, 22, 25, 28, 30, 37, 38, 39, 40, 42, 44, 57, 59, 61, 62, 67, 71, 75, 76, 77, 82, 83, 86, 87, 92, 94, 95]

In [97]:
# Players Who play all sports
set_C = set(C)
set_F = set(F) 
set_H = set(H)
set_all = set_C.intersection(set_F).intersection(set_H)
set_all

{40, 95}

In [98]:
set_Cricket_Hockey_Not_Football = set_C.intersection(set_H) - set_F
set_Cricket_Hockey_Not_Football

{20, 21, 25, 62, 67, 71, 75, 76, 82}

In [99]:
set_exactly_two_sports = (set_C.intersection(set_F) - set_H).union((set_C.intersection(set_H) - set_F)).union((set_F.intersection(set_H) - set_C))
set_exactly_two_sports

{7,
 20,
 21,
 22,
 25,
 30,
 32,
 34,
 39,
 43,
 44,
 62,
 67,
 68,
 71,
 75,
 76,
 77,
 82,
 90,
 93,
 94}

In [100]:
set_Not_Playing_Any_Sport = set(range(1, 101)) - (set_C.union(set_F).union(set_H))
set_Not_Playing_Any_Sport

{2,
 3,
 4,
 6,
 11,
 15,
 19,
 23,
 33,
 41,
 46,
 49,
 50,
 51,
 52,
 54,
 55,
 63,
 64,
 66,
 70,
 79,
 84,
 85,
 88,
 89,
 91,
 98,
 100}

#### Q2. The `netflix` dictionary contains a list of 100 titles along with their total number of views in the past. Based on the keys and values provided in this dictionary, answer the questions given below.

#### 1. There's an Indian movie in the dictionary named `Do Paise Ki Dhoop Chaar Aane Ki Baarish`. What is the number of views for this movie?
- 90,854
- 658,824
- 1,023,597
- 2,770,879

#### 2. Which of the shows is the most and least popular in terms of number of views? </br> 
(Hint: Use the `key` argument in the max() and min() functions.)
- Monkey Twins, Maynard
- Gaga: Five Foot Two, Hilda
- Gerald's Game, White Island
- Rafinha Bastos: Ultimatum, The First Line

#### Netflix has just recieved the number of views for the last week as well. This data is given below, in the form of a dictionary

#### 3. Netflix has just recieved the number of views for the last week as well. Add these views to the total views and find the most popular title in terms of views. Also find out how many views this title has? 
- Title: Deliha 2, Views: 3943452
- Title: Dragons: Rescue Riders, Views: 3996388
- Title: Rafinha Bastos: Ultimatum, Views: 3575445
- Title: Gaga: Five Foot Two, Views: 3756188

In [101]:
netflix = {'The Debt Collector': 1821195, 'Act of Vengeance': 2804479, 'Paradise Lost': 2195477, "Gerald's Game": 3650626, 'Long Shot': 638440, 'Mak Cun': 1010311, 'Our Souls at Night': 3028705, 'Out of Thin Air': 2681938, "Paul Hollywood's Big Continental Road Trip": 230689, 'Satu Hari': 1012350, 'Monster High: Boo York, Boo York': 1526025, 'Cultivating the Seas: History and Future of the Full-Cycle Cultured Kindai Tuna': 2762103, 'Domino': 872663, 'TUNA GIRL': 2574816, '5CM': 2647713, 'Animal World': 220789, 'Hold the Dark': 2307432, 'Lessons from a School Shooting: Notes from Dunblane': 2419534, 'Made in Mexico': 3653712, 'Single': 239278, 'The 3rd Eye': 196138, 'The Sinking Of Van Der Wijck': 2831856, 'Two Catalonias': 1337119, 'Bobby Sands: 66 Days': 2005623, 'Bard of Blood': 744998, 'Deliha 2': 3638900, 'Dragons: Rescue Riders': 3241239, 'In the Shadow of the Moon': 1213329, 'Skylines': 1840094, 'Sturgill Simpson Presents Sound & Fury': 1915540, 'The Politician': 1019394, 'Weeds on Fire': 2273090, 'Much Loved': 3039852, 'Joseph: King of Dreams': 1734449, 'Malaal': 1926128, 'The Grandmaster': 2549410, 'The Inmate': 130965, 'The Hurricane Heist': 2191538, 'Def Comedy Jam 25': 1392697, 'Restless Creature: Wendy Whelan': 2474412, 'Print the Legend': 548250, 'Birders': 3478883, 'Furie': 2755115, 'Leap!': 1401638, 'Oh! Baby (Malayalam)': 839139, 'Oh! Baby (Tamil)': 2691505, 'USS Indianapolis: Men of Courage': 3286014, 'A Wrinkle in Time': 1258861, 'Teach Us All': 2428947, 'White Island': 1152905, 'Inside Man: Most Wanted': 2812661, 'Jeff Dunham: Beside Himself': 2930368, 'China Salesman': 3377292, 'Swearnet: The Movie': 949689, 'The Bar': 620655, 'Manmadhudu 2': 1842761, 'Team Kaylie': 359856, 'Under the Eiffel Tower': 2298237, 'Audrie & Daisy': 1573055, 'Iliza Shlesinger: Confirmed Kills': 365220, 'BONDING': 1664242, 'Do Paise Ki Dhoop Chaar Aane Ki Baarish': 2770879, '20 Feet From Stardom': 2931730, 'In Darkness': 3248749, 'Gaga: Five Foot Two': 3719550, 'The Bad Batch': 3656264, 'SMOSH: The Movie': 3697506, 'King of Boys': 584112, 'Merry Men: The Real Yoruba Demons': 2035595, "Sarah's Key": 1337902, 'The Wedding Party 2: Destination Dubai': 1471204, 'Vagabond': 1600432, 'Battlefish': 723021, 'DRAGON PILOT: Hisone & Masotan': 602919, 'Hilda': 54948, 'Maniac': 1348196, 'Quincy': 2601704, 'Rafinha Bastos: Ultimatum': 3469996, 'The Good Cop': 2265521, 'Between Two Ferns: The Movie': 3146508, 'Criminal: France': 2021409, 'Criminal: Germany': 658824, 'Criminal: Spain': 3078634, 'Criminal: UK': 2721398, 'Daddy Issues': 2119035, "Inside Bill's Brain: Decoding Bill Gates": 1755104, 'The Hockey Girls': 2000507, 'Travel Mates 2': 707260, 'True: Tricky Treat Day': 3213199, 'Two Sentence Horror Stories': 2438329, 'Mad World': 2281773, 'Mobile Suit Gundam UC': 778879, 'The Bund': 1729892, 'The First Line': 674591, 'Maynard': 84986, 'Monkey Twins': 3277179, 'Bitcoin Heist': 1450158, 'I Am Not Madame Bovary': 2763830, 'Vincent N Roxxy': 1961810, "Chef's Table: France": 2065738}
netflix_last_week = {'The Debt Collector': 229218, 'Act of Vengeance': 191468, 'Paradise Lost': 167846, "Gerald's Game": 113298, 'Long Shot': 15190, 'Mak Cun': 244581, 'Our Souls at Night': 188095, 'Out of Thin Air': 183961, "Paul Hollywood's Big Continental Road Trip": 207967, 'Satu Hari': 226211, 'Monster High: Boo York, Boo York': 265919, 'Cultivating the Seas: History and Future of the Full-Cycle Cultured Kindai Tuna': 192246, 'Domino': 190538, 'TUNA GIRL': 301819, '5CM': 154371, 'Animal World': 228227, 'Hold the Dark': 222938, 'Lessons from a School Shooting: Notes from Dunblane': 256580, 'Made in Mexico': 199790, 'Single': 155517, 'The 3rd Eye': 251349, 'The Sinking Of Van Der Wijck': 153797, 'Two Catalonias': 189422, 'Bobby Sands: 66 Days': 202461, 'Bard of Blood': 241928, 'Deliha 2': 304552, 'Dragons: Rescue Riders': 155149, 'In the Shadow of the Moon': 222999, 'Skylines': 118737, 'Sturgill Simpson Presents Sound & Fury': 43590, 'The Politician': 11902, 'Weeds on Fire': 243382, 'Much Loved': 190123, 'Joseph: King of Dreams': 46104, 'Malaal': 70961, 'The Grandmaster': 44908, 'The Inmate': 19574, 'The Hurricane Heist': 167696, 'Def Comedy Jam 25': 208075, 'Restless Creature: Wendy Whelan': 22976, 'Print the Legend': 161584, 'Birders': 257668, 'Furie': 282266, 'Leap!': 124338, 'Oh! Baby (Malayalam)': 18203, 'Oh! Baby (Tamil)': 131481, 'USS Indianapolis: Men of Courage': 76558, 'A Wrinkle in Time': 169365, 'Teach Us All': 50378, 'White Island': 299779, 'Inside Man: Most Wanted': 123346, 'Jeff Dunham: Beside Himself': 283561, 'China Salesman': 182041, 'Swearnet: The Movie': 63809, 'The Bar': 41243, 'Manmadhudu 2': 261349, 'Team Kaylie': 101283, 'Under the Eiffel Tower': 83650, 'Audrie & Daisy': 106092, 'Iliza Shlesinger: Confirmed Kills': 255103, 'BONDING': 202683, 'Do Paise Ki Dhoop Chaar Aane Ki Baarish': 32329, '20 Feet From Stardom': 165178, 'In Darkness': 95259, 'Gaga: Five Foot Two': 36638, 'The Bad Batch': 197820, 'SMOSH: The Movie': 196519, 'King of Boys': 49332, 'Merry Men: The Real Yoruba Demons': 293229, "Sarah's Key": 178523, 'The Wedding Party 2: Destination Dubai': 51211, 'Vagabond': 116831, 'Battlefish': 5448, 'DRAGON PILOT: Hisone & Masotan': 281873, 'Hilda': 21348, 'Maniac': 268187, 'Quincy': 139696, 'Rafinha Bastos: Ultimatum': 105449, 'The Good Cop': 73230, 'Between Two Ferns: The Movie': 135600, 'Criminal: France': 243469, 'Criminal: Germany': 285211, 'Criminal: Spain': 45184, 'Criminal: UK': 117056, 'Daddy Issues': 267329, "Inside Bill's Brain: Decoding Bill Gates": 64083, 'The Hockey Girls': 114146, 'Travel Mates 2': 21088, 'True: Tricky Treat Day': 116504, 'Two Sentence Horror Stories': 274471, 'Mad World': 225244, 'Mobile Suit Gundam UC': 47306, 'The Bund': 146872, 'The First Line': 148861, 'Maynard': 87252, 'Monkey Twins': 199274, 'Bitcoin Heist': 41105, 'I Am Not Madame Bovary': 57841, 'Vincent N Roxxy': 207453, "Chef's Table: France": 200536}

In [102]:
netflix_df = pd.DataFrame(list(netflix.items()), columns=['Title', 'Total Views'])
netflix_last_week_df = pd.DataFrame(list(netflix_last_week.items()), columns=['Title', 'Last Week Views'])

In [103]:
netflix_df.head()

                Title  Total Views
0  The Debt Collector      1821195
1    Act of Vengeance      2804479
2       Paradise Lost      2195477
3       Gerald's Game      3650626
4           Long Shot       638440

In [104]:
netflix_last_week_df.head()

                Title  Last Week Views
0  The Debt Collector           229218
1    Act of Vengeance           191468
2       Paradise Lost           167846
3       Gerald's Game           113298
4           Long Shot            15190

In [105]:
# Views of the movie "Do Paise Ki Dhoop Chaar Aane Ki Baarish" in the last week
netflix_df[netflix_df['Title'] == 'Do Paise Ki Dhoop Chaar Aane Ki Baarish']

                                      Title  Total Views
61  Do Paise Ki Dhoop Chaar Aane Ki Baarish      2770879

In [106]:
# Show which have the maximum views
netflix_df[netflix_df['Total Views'] == netflix_df['Total Views'].max()]

                  Title  Total Views
64  Gaga: Five Foot Two      3719550

In [107]:
# Show which have the minimum views
netflix_df[netflix_df['Total Views'] == netflix_df['Total Views'].min()]

    Title  Total Views
74  Hilda        54948

In [108]:
netflix_df['Total Views'] = netflix_df['Total Views'] + netflix_last_week_df['Last Week Views']
netflix_df.head()

                Title  Total Views
0  The Debt Collector      2050413
1    Act of Vengeance      2995947
2       Paradise Lost      2363323
3       Gerald's Game      3763924
4           Long Shot       653630

In [109]:
# After Adding last week views, Show which have the maximum views
netflix_df[netflix_df['Total Views'] == netflix_df['Total Views'].max()]

       Title  Total Views
25  Deliha 2      3943452

#### Q3. Create a dictionary where the keys are multiples of 3 among the first 100 natural numbers and each value is the cube of the key.

In [110]:
df = {i:i**3 for i in range(3,101,3)}
df

{3: 27,
 6: 216,
 9: 729,
 12: 1728,
 15: 3375,
 18: 5832,
 21: 9261,
 24: 13824,
 27: 19683,
 30: 27000,
 33: 35937,
 36: 46656,
 39: 59319,
 42: 74088,
 45: 91125,
 48: 110592,
 51: 132651,
 54: 157464,
 57: 185193,
 60: 216000,
 63: 250047,
 66: 287496,
 69: 328509,
 72: 373248,
 75: 421875,
 78: 474552,
 81: 531441,
 84: 592704,
 87: 658503,
 90: 729000,
 93: 804357,
 96: 884736,
 99: 970299}

#### Q4. Write a code in one line to print following results:

#### a.	i/p: List 1=[abc] ,list2=[def]
#### o/p: ['ad', 'ae', 'af', 'bd', 'be', 'bf', 'cd', 'ce', 'cf']

#### b.	i/p: List 1=[acdb]
#### o/p: {'A': 'aaa', 'C': 'ccc', 'B': 'bbb', 'D': 'ddd'}

In [111]:
list1 = ['a','b','c']
list2 = ['d','e','f']

[i+j for i in list1 for j in list2]

['ad', 'ae', 'af', 'bd', 'be', 'bf', 'cd', 'ce', 'cf']

In [112]:
list1x = ['a','c','d','b']
[i*3 for i in list1x]

['aaa', 'ccc', 'ddd', 'bbb']

#### Q5. Write a python code to Make the following 4x7 array called nolathat starts with 1 and steps by 2. However,note that the first element in each row is always 4 more than the last element in the previous row

In [113]:
nolathat = np.arange(1,57,2).reshape(4,7)
nolathat

array([[ 1,  3,  5,  7,  9, 11, 13],
       [15, 17, 19, 21, 23, 25, 27],
       [29, 31, 33, 35, 37, 39, 41],
       [43, 45, 47, 49, 51, 53, 55]])

#### Q6. Define aroux array as a 1-D array such that, when it's reversed, it represents the sequence
#### Of square numbers 1,4,9,16,...with 0s  Inter  woven  between them.# roux array of length 5
#### [9 0 4 0 1]
#### #roux array of length 8 [ 0 16090401]

In [114]:
def squares(n):
    squares = np.arange(1, n // 2 + 2) ** 2
    result = np.zeros(n, dtype=int)
    result[::-2] = squares[:len(result[::2])]
    return result

In [115]:
squares(5)

array([9, 0, 4, 0, 1])

In [116]:
squares(8)

array([ 0, 16,  0,  9,  0,  4,  0,  1])

#### Q7. Write a NumPy program to test whether each element of a 1-D array is also present in a second array.
#### Expected Output:
#### Array1: [ 0 10 20 40 60]
#### Array2: [0, 40]
#### Compare each element of array 1 and array2 Output: [ True False False True False]

In [117]:
array1 = np.array([0,10,20,40,60])
array2 = np.array([0,40])
np.isin(array1, array2)

array([ True, False, False,  True, False])

#### Q8. Write a NumPy program to get the unique elements of an array Expected Output:
#### Original array:
#### [10 10 20 20 30 30]
#### Unique elements of the above array: [10 20 30]
#### Original array:
#### [[1 1]
#### [2 3]]
#### Unique elements of the above array: [1 2 3]

In [118]:
arrq8 = np.array([10,10,20,20,30,30])
np.unique(arrq8)

array([10, 20, 30])

In [119]:
arr2q8 = np.array([[1,1],[2,3]])
np.unique(arr2q8)

array([1, 2, 3])

#### Q9. Write a NumPy program to sort an along the first, last axis of an array.
#### Sample array: [[2,5],[4,4]]
#### Expected Output:
#### Original array:
#### [[4 6]
#### [2 1]]
#### Sort a long the first axis: [[2 1]
#### [4 6]]
#### Sort along the last axis:
#### [[1 2]
#### [4 6]]

In [120]:
arr1q9 = np.array([[4,6],[2,1]])
arr1q9.sort(axis=0)
arr1q9

array([[2, 1],
       [4, 6]])

In [121]:
arr1q9 = np.array([[4,6],[2,1]])
arr1q9.sort(axis=1)
arr1q9

array([[4, 6],
       [1, 2]])

#### Q10. Write a program to count the occurrence of a specified item in a given NumPy array.
#### Sample Output:
#### Original array:
#### [10 20 20 20 20 0 20 30 30 30 0 0 20 20 0]
#### [4,1,7,3]
#### Write a NumPy program to remove nan values from a given array.
#### Sample Output:
#### Original array:
#### [200.300.nannannan700.] After removing nan values: [200. 300. 700.]

In [122]:
arr1q10 = np.array([10,20,20,20,20,0,20,30,30,30,0,0,20,20,0])
value,counts = np.unique(arr1q10, return_counts=True)
value,counts

(array([ 0, 10, 20, 30]), array([4, 1, 7, 3]))

In [123]:
arr1q10[~np.isnan(arr1q10)]

array([10, 20, 20, 20, 20,  0, 20, 30, 30, 30,  0,  0, 20, 20,  0])

#### Q11. Write a NumPy program to calculate percentiles for a sequence or single-dimensional NumPy array.
#### Sample Output:
#### 50thpercentile(median): 3.0
#### 40th percentile:
#### 2.6
#### 90th percentile:
#### 4.6

In [124]:
arr1q11 = np.array([1, 2, 3, 4, 5])
print(np.percentile(arr1q11, 50))  # 50th percentile (median)
print(np.percentile(arr1q11, 40))  # 25th percentile (first quartile)
print(np.percentile(arr1q11, 90))  # 75th percentile (third quartile)

3.0
2.6
4.6

#### Q12. Write a NumPy program to find in dices of elements equal to zero in a NumPy array. Sample Output:
#### Original array:
#### [1 0 2 0 3 0 4 5 6 7 8]
#### Indices of elements equal to zero of the said array: [1 3 5]

In [125]:
arr1q12 = np.array([1,0,2,0,3,0,4,5,6,7,8])
np.where(arr1q12 == 0)[0]

array([1, 3, 5])

#### Q13. Write a NumPy program to get the in dices of the sorted elements of a given array. Expected Output:
#### Original array:
#### [1023 5202 6230 1671 1682 5241 4532] 	
#### In dices of the sorted elements of a given array: [0 3 4 6 1 5 2]

In [126]:
arr1q13 = np.array([1023,5202,6230,1671,1682,5241,4532])
np.argsort(arr1q13)

array([0, 3, 4, 6, 1, 5, 2])

#### Q14. Write a NumPy program to partition a given array in a specified position and move all the
#### smaller elements values to the left of the partition, and the remaining values to the right, in
#### arbitrary order (based on random choice).
#### Sample output:
#### Original array:
#### [ 70 50 20 30 -11 60 50 40]
#### Afterpartitioningon4theposition: [-11 30 20 40 50 50 60 70]

In [127]:
arr1q14 = np.array([70,50,20,30,-11,60,50,40])
np.partition(arr1q14, 4)

array([-11,  20,  30,  40,  50,  50,  60,  70])

#### Q15. Compute the euclidean distance between two arrays a and b. Input:
#### [1,2,3,4,5]
#### [4,5,6,7,8]
#### Euclidean distance is: 6.7082

In [128]:
arr1q15 = np.array([1,2,3,4,5])
arr2q15 = np.array([4,5,6,7,8])
np.linalg.norm(arr1q15 - arr2q15)

np.float64(6.708203932499369)

#### Q16. Find all the peaks in a 1D numpy array a. Peaks are points surrounded by smaller values on
#### both sides.
#### Input:
#### array([1, 3, 7, 1, 2, 6, 0, 1])
#### Desired Output:
#### array( [2, 5])
#### where, 2 and 5 are the positions of peak values 7 and 6.

In [129]:
arr1q16 = np.array([1,3,7,1,2,6,0,1])
np.where((arr1q16[1:-1]>arr1q16[:-2]) & (arr1q16[1:-1]>arr1q16[2:]))[0] + 1

array([2, 5])

#### Q17. Find the index of nth repetition of number i .
#### Inputs
#### array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
#### n=5(fromuser) 
#### i = 1 (from user) Output
#### 8

In [130]:
arr1q17 = np.array([1,2,1,1,3,4,3,1,1,2,1,1,2])
nq17 = 5
iq17 = 1
np.where(arr1q17 == iq17)[0][nq17-1]

np.int64(8)

#### Q18. Write a NumPy program to calculate the difference between neighboring elements,
#### element-wise, and prepend [0, 0] and append[200] to a given array.
#### Sample output:
#### Original array:
#### [1 3 5 7 0]
#### Difference between neighboring elements, element-wise, and prepend [0, 0] and
#### append[200] to the said array: 
#### [ 0 0 2 2 2 -7 200]

In [131]:
arr1q18 = np.array([1,3,5,7,0])
np.diff(arr1q18,prepend=[0,0],append=[200])

array([  0,   1,   2,   2,   2,  -7, 200])

#### Q19. Write a NumPy program to round elements of the array to the nearest integer, and then
#### calculate the absolute value element wise.
#### Sample Output:
#### Original array:
#### [-0.7 -1.5 -1.7 0.3 1.5 1.8 2. ]
#### Round elements of the array to the nearest integer: [1. 2. 2. 0. 2. 2. 2.]

In [132]:
arr1q19 = np.array([-0.7,-1.5,-1.7,0.3,1.5,1.8,2.0])
rounded = np.round(arr1q19)
np.abs(rounded)

array([1., 2., 2., 0., 2., 2., 2.])